### ISSUE TITLE
Cannot download .bin file using the online compiler

### ISSUE THREAD

**Issue by karenyen10** [ARMmbed/mbed-os-example-wifi#105]
When compiling, I am unable to download and get the following error:

>Error: Identifier "wifi" is undefined in "main.cpp", Line: 147, Col: 25

which references this line:

>count = scan_demo(&wifi);

**Comment by SeppoTakalo** [comment]
What target and what value you set in the mbed_app.json as the shield?

**Comment by SeppoTakalo** [comment]
Follow the guide https://github.com/ARMmbed/mbed-os-example-wifi#getting-started step two.

**Comment by karenyen10** [comment]
Oh wow, yeah, I forgot to do step 2. Thank you.
