### ISSUE TITLE
auto-install always fails

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-os-example-wifi#139]
With the new version of mbed, you always get the following error:
```
[mbed] Auto-installing missing Python modules...
[mbed] WARNING: Unable to auto-install required Python modules.
       The mbed OS tools in this program require the following Python modules: git
       You can install all missing modules by running "pip install -r requirements.txt" in "/home/jim/AvNet/mbed-os-example-wifi/mbed-os"
       On Posix systems (Linux, Mac, etc) you might have to switch to superuser account or use "sudo"

```
I know those modules have been installed because i  did a:
`sudo -H pip install -r requirements.txt`
and it reported that is was successfully installed prior to issuing the:
`mbed add esp8266-driver`
command.  In spite of that, I always get the same error when compiling or adding libraries. It seems like the mbed command isn't working correctly for some reason.  Even though that error/warning is displayed, everything appears to work correctly.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4084

**Comment by SeppoTakalo** [comment]
Hi @jflynn129 
Your command output does not contain any error. Just warning about pip.

That should be recorded in the Mbed OS or Mbed CLI repository for studying.

What comes to build failure, can you try not adding ESP driver as the current Mbed OS release already contains ESP driver.
Documentation seems to be outdated regarding that. I'll fix it.

**Comment by 0xc0170** [comment]
This warning is already tracked in Mbed CI (latest version should have addressed it). https://github.com/ARMmbed/mbed-cli/issues/782

**Comment by jflynn129** [comment]
Ok, I did find that the driver was already there after investigating a little further, but the prolific warning messages are very irritating to a user, kind of like saying "your breathing" ever time you take a breath. But I'll close this given that it is an already know concern.
