### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by cwq9999** [ARMmbed/mbed-os-example-wifi#143]
Are there plans to add an ESP32 interface?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4114

**Comment by SeppoTakalo** [comment]
There are no plans to add more WiFi drivers here, as any driver should work with this, as long as they work with Mbed OS.

If you have the driver that works, just `mbed add <driver>` and modify `mbed_app.json` accordingly.

The author of ESP32 driver should be able to guide what settings the driver required from `mbed_app.json`, if any.
