### ISSUE TITLE
[OOB 5.13] Example fails in scan on Nucleo_F411RE + ESP8266

### ISSUE THREAD

**Issue by linlingao** [ARMmbed/mbed-os-example-wifi#161]
The example fails with Nucleo_F411RE+ESP8266. I tried two ESP8266 modules.

WiFi example
Mbed OS version 5.13.0

Scan:
scan() failed with return value: -3012
No WIFI APs found - can't continue further.

mbed compile -m nucleo_f411re -t arm --app-config mbed_app_esp8266.json -c

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4363

**Comment by SeppoTakalo** [comment]
How did you connect and configure the ESP shield?

Default configuration does not seem to configure pins for F411RE: https://github.com/ARMmbed/mbed-os-example-wifi/blob/master/mbed_app_esp8266.json

-3012 is Device error, so it might be that the device is not in the correct serial port at all.

**Comment by SeppoTakalo** [comment]
Oh.. actually, F411RE seems to be using D8/D2 pins by default: https://github.com/ARMmbed/mbed-os/blob/master/components/wifi/esp8266-driver/mbed_lib.json#L59

**Comment by linlingao** [comment]
Yes, pins are defined in the mbed_lib.json. No hardware flow control pins are defined though, do you expect it to work without hardware flow control?

**Comment by SeppoTakalo** [comment]
It should work without flow control.

What pins did you use?
Please note that TX and RX pins have to be crossed. So the TX pin in ESP is actually Serial RX pin on Mbed side.

**Comment by linlingao** [comment]
I'm closing this issue because using the ESP8266 shield has fried my F411RE board. Someone else also mentioned it happened to him too. I don't want to fry another board. I've switched to ST IDW04A1.
