### ISSUE TITLE
[OOB 5.13] mbed-os-example-wifi README serial output needs update

### ISSUE THREAD

**Issue by linlingao** [ARMmbed/mbed-os-example-wifi#162]
The HTTP GET has been removed from the example.

{{Sending HTTP request to www.arm.com... }}

{{sent 38 [GET / HTTP/1.1] }}

recv 64 [HTTP/1.1 301 Moved Permanently]

Done

Output from latest code:

MAC: C4:7F:51:8C:6A:AA
IP: 192.168.1.21
Netmask: 255.255.255.0
Gateway: 192.168.1.1
RSSI: -69

Done

Please removed the 3 lines beginning from "Sending".

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4362

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/mbed-os-example-wifi/commit/e37daa3085189c7aebab502f5d2deff1a07321da

Thank you for the report.
