### ISSUE TITLE
master branch has non-working Mbed OS tagged in.

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-os-example-wifi#184]
Related to.
https://github.com/ARMmbed/mbed-os/issues/12137

**Comment by korjaa** [comment]
Wrong project...

**Comment by korjaa** [comment]
Steps to reproduce.
1. `pip install mbed-cli`
1. `mbed import mbed-os-example wifi`
1. `pip install -r mbed-os/requirements.txt`
1. -> fail.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2370

**Comment by AnttiKauppila** [comment]
Version updated
