### ISSUE TITLE
Example uses master for mbed-os, not an actual release of mbed-os

### ISSUE THREAD

**Issue by ifyall** [ARMmbed/mbed-os-example-wifi#188]
PR #187 changed the mbed-os.lib to pull master instead of a specific release. This doesn't seem correct, as master is not a release of mbed-os. Instead, the .lib should be using the 'latest' tag.

Thank you,

Ian

**Comment by michalpasztamobica** [comment]
@AnttiKauppila , please comment.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2456

**Comment by 0xc0170** [comment]
The repository was deprecated. We are closing all issues/pull requests now to archive it.
