### ISSUE TITLE
[OoB 6.0.0-RC2] No instruction on how to import WiFi driver to the online compiler

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-os-example-wifi#191]
The README file shows the WiFi driver (not part of mbed-os) can be added with `mbed add` in CLI. But it lacks the instruction that with the online compiler the way to do it is Import -> Libraries -> Click here to import from URL.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2461

**Comment by 0xc0170** [comment]
The repository was deprecated. We are closing all issues/pull requests now to archive it.
