### ISSUE TITLE
scount isssue.  " sizeof sbuffer" -> " sizeof sbuffer-1" 

### ISSUE THREAD

**Issue by okoshi3** [ARMmbed/mbed-os-example-wifi#31]
simple issue

   int scount = socket.send(sbuffer, sizeof sbuffer);
              | 
             V
   int scount = socket.send(sbuffer, sizeof sbuffer-1);

Thanks

**Comment by bulislaw** [comment]
Sorry I've missed this issue before. Can you give use more details? Is sending the final 0 byte an issue?
