### ISSUE TITLE
Should note mbed Online Compiler in README

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-wifi#53]
Right now it seems that you can only use this repository with mbed CLI, which is not true.

**Comment by SeppoTakalo** [comment]
I agree with your point but none of the examples actually refer to online compiler so I'm closing this as it follows the same structure as rest of them.

These examples however are part of "mbed-os-examples" repository in Developer site: https://os.mbed.com/teams/mbed-os-examples/code/

But I'm unaware of which documentation actually points to that page.
