### ISSUE TITLE
Cannot build for K64F - ESP8266 with new Morpho form factor check

### ISSUE THREAD

**Issue by kegilbert** [ARMmbed/mbed-os-example-wifi#61]
https://github.com/ARMmbed/mbed-os-example-wifi/blob/0228d63e9b7483a04f19aa639a800a90298019a8/main.cpp#L33

This change from https://github.com/ARMmbed/mbed-os-example-wifi/commit/0228d63e9b7483a04f19aa639a800a90298019a8 means a device has to have both an Arduino and Morpho form factor. Out of the box, a K64F with an ESP8266 will not compile. 

@bulislaw

**Comment by MarceloSalazar** [comment]
@bulislaw can we get this fixed and land a PR in the 5.6 oob branch asap please?

**Comment by MarceloSalazar** [comment]
Thanks @SeppoTakalo !
