### ISSUE TITLE
Compiling the example with online IDE for realtek_rtl8195am board throw out errors.

### ISSUE THREAD

**Issue by jamesbeyond** [ARMmbed/mbed-os-example-wifi#91]
I am using mbed online IDE to compile the example for realtek_rtl8195am board. online IDE throw compiling errors:

Steps:
1. Open mbed IDE, import `mbed-os-example-wifi example`, and update it to 5.8.0 rc
2. select `realtek_rtl8195am` platform.
3. compiling.

![realtek_rtl8195am](https://user-images.githubusercontent.com/34235743/37111633-13f46648-2238-11e8-8957-7597a9d63217.png)

**Comment by theotherjimmy** [comment]
Yeah, you're not using the RC.

**Comment by jamesbeyond** [comment]
@theotherjimmy You mean to update the example with 5.8.0-rc branch? I did that after import the example, however it is the same result. I can update the summary to reflect that.

BTW, I only update to the RC in the example level, however, the mbed-os within the example seems not got updated with the example from the online compiler. This was mentioned in the Slack threads by Seppo Takalo

**Comment by theotherjimmy** [comment]
No, I mean update mbed-os. That's a bug in 5.7.6, I think.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3671

**Comment by SeppoTakalo** [comment]
Not visible anymore, so fixed somewhere in Mbed OS 5.8.
