### ISSUE TITLE
K66F with ESP8266 connection error

### ISSUE THREAD

**Issue by cargro** [ARMmbed/mbed-os-example-wifi#95]
using mbed-os-5.8-oob branch

mbed_app.json file:

![image](https://user-images.githubusercontent.com/36272895/37657938-3d92c9f2-2c44-11e8-9584-c7f67c8ac310.png)

serial output: 
![image](https://user-images.githubusercontent.com/36272895/37658186-dd29cc72-2c44-11e8-9ba4-7e8d16a8d843.png)

**Comment by SeppoTakalo** [comment]
Did you re-try it?
Connecting to WiFi AP is not 100% success every time.

Also, you blacked you the WiFi AP list so I cannot very whether the target was even in range.

Anyway, I cannot replicate this in our internal CI. I can provide you a link on separate email.

**Comment by ashok-rao** [comment]
@SeppoTakalo .. I confirm that the AP was in range and we did re-try a few times.. we are using the ESP8266 + K66F.. we also redefined the wifi-tx/rx pins in mbed_app.json just to be 100% sure it was not something related to pins.. we also tried using a mobile phone as hotspot (with respective SSID/pwd).. but even that did not connect..

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3669

**Comment by SeppoTakalo** [comment]
I'm closing this as I'm not seeing the same issues in our CI:
https://jenkins-internal.mbed.com/view/IP%20Core/job/mbed-os-wifi-test/compiler=ARM,protocol=IPv4,target=K64F,variant=ESP8266/HTML_20Report/
